---
version: 2
project_name: certinfo
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/certinfo/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}
      - -X main.Commit={{ .FullCommit }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
homebrew_casks:
  - repository:
      owner: containeroo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      branch: master
    homepage: https://containeroo.ch
    description: Get information about the certificate from one or more hostnames
    license: GNU General Public License v3.0
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/certinfo"]
          end
