---
project_name: certinfo
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/certinfomain.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
brews:
  - name: certinfo
    tap:
      owner: containeroo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://containeroo.ch
    description: Get information about the certificate from one or more hostnames
    license: GNU General Public License v3.0
    test: |
      system "#{bin}/certinfo --version"
    dependencies:
      - name: go
        type: optional
    install: |-
      bin.install "certinfo"
